// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_FHXeBcJCMet0b12e7jSHdh1e3sj65DY',
    appId: '1:430187763839:web:9693312bf0c2cd6b1b874a',
    messagingSenderId: '430187763839',
    projectId: 'firefire-3b680',
    authDomain: 'firefire-3b680.firebaseapp.com',
    databaseURL: 'https://firefire-3b680-default-rtdb.firebaseio.com',
    storageBucket: 'firefire-3b680.firebasestorage.app',
    measurementId: 'G-NWM43SP94Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsbToeRN0Q2tvTbXjSarjMs9qY6erufqI',
    appId: '1:430187763839:android:8409d4916ca3da5f1b874a',
    messagingSenderId: '430187763839',
    projectId: 'firefire-3b680',
    databaseURL: 'https://firefire-3b680-default-rtdb.firebaseio.com',
    storageBucket: 'firefire-3b680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCotIFQ0ChV0eOROh199ydKQcsREU0d6lo',
    appId: '1:430187763839:ios:815617ea2648584f1b874a',
    messagingSenderId: '430187763839',
    projectId: 'firefire-3b680',
    databaseURL: 'https://firefire-3b680-default-rtdb.firebaseio.com',
    storageBucket: 'firefire-3b680.firebasestorage.app',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCotIFQ0ChV0eOROh199ydKQcsREU0d6lo',
    appId: '1:430187763839:ios:815617ea2648584f1b874a',
    messagingSenderId: '430187763839',
    projectId: 'firefire-3b680',
    databaseURL: 'https://firefire-3b680-default-rtdb.firebaseio.com',
    storageBucket: 'firefire-3b680.firebasestorage.app',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_FHXeBcJCMet0b12e7jSHdh1e3sj65DY',
    appId: '1:430187763839:web:abf11b35e58621071b874a',
    messagingSenderId: '430187763839',
    projectId: 'firefire-3b680',
    authDomain: 'firefire-3b680.firebaseapp.com',
    databaseURL: 'https://firefire-3b680-default-rtdb.firebaseio.com',
    storageBucket: 'firefire-3b680.firebasestorage.app',
    measurementId: 'G-KQ16LYQTN9',
  );
}
